name: "Multi-head Attention Test"

layers:
  - type: Input
    name: "input"
    output_shape: [10, 256]
    
  - type: MultiHeadAttention
    input_size: 256
    output_size: 256
    sequence_length: 10
    num_heads: 2
    initializer: xavier

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 8
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Multi-head-Attention basic test"
