name: "Multi Layer Dense NN"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 256]
    
  - type: Dense
    input_size: 256
    output_size: 256
    activation: relu
    initializer: he

  - type: BatchNormalization
    input_size: 256
    output_size: 256
    learning_rate: 5e-6

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: he

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 2
  batch_size: 20

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Multi Layer Dense NN"
