name: "OCR Complete"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 784]
    
  - type: Dense
    input_size: 784
    output_size: 512
    activation: relu
    initializer: he

  - type: BatchNormalization
    input_size: 512
    output_size: 512
    epsilon: 1e-5

  - type: Dropout
    rate: 0.1
    input_size: 512
    output_size: 512

  - type: Dense
    input_size: 512
    output_size: 256
    activation: relu
    initializer: he

  - type: BatchNormalization
    input_size: 256
    output_size: 256
    epsilon: 1e-5

  - type: Dropout
    rate: 0.1
    input_size: 256
    output_size: 256

  - type: Dense
    input_size: 256
    output_size: 10
    activation: softmax
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 4
  batch_size: 64

dataset:
  type: "mnist"
  images: "train-images-idx3-ubyte"
  labels: "train-labels-idx1-ubyte"

metadata:
  author: "James Couch"
  description: "Combined OCR pipeline with Dropout and Batch Normalization"
