name: "Pass Through Test"

layers:
  - type: Input
    name: "input"
    output_shape: [2, 256]
    
  - type: Flatten
    name: "flatten"
    input_shape: [2, 256]
    output_size: 512
    
  - type: Dense
    name: "dense"
    input_size: 512
    output_size: 512
    activation: gelu
    initializer: he
    
  - type: Reshape
    name: "reshape"
    input_size: 512
    output_shape: [2, 256]
    
  - type: Dense
    name: "final_dense"
    input_size: 512
    output_size: 256
    activation: linear
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    accumulation_interval: 4
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 5
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Tests that flatten and reshape layers simply noop."
