name: "Residual Connection"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 256]
    
  - type: Dense
    input_size: 256
    output_size: 256
    activation: relu
    initializer: he
    name: "dense_1"

  - type: LayerNormalization
    input_shape: [1, 256]
    output_shape: [1, 256]
    epsilon: 1e-5
    
  - type: ResidualConnection
    input_size: 256
    output_size: 256
    from_layer: "input"
    
  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: xavier
    name: "dense_2"
    
  - type: ResidualConnection
    input_size: 256
    output_size: 256
    from_layer: "dense_1"

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.001
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 5
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Residual Connection"
