name: "Self Attention Test"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 256]
    
  - type: SelfAttention
    input_size: 256
    output_size: 256
    sequence_length: 10
    initializer: xavier

  - type: Dense
    input_size: 256
    output_size: 256
    activation: linear
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 2
  batch_size: 2

dataset:
  type: "function"

metadata:
  author: "James Couch"
  description: "Self-Attention basic test"
