name: "Stable OCR"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 784]
    
  - type: Dense
    input_size: 784
    output_size: 128
    activation: relu
    initializer: he
    
  - type: BatchNormalization
    input_size: 128
    output_size: 128

  - type: Dense
    input_size: 128
    output_size: 10
    activation: softmax
    initializer: xavier

training:
  optimizer:
    type: adam
    learning_rate: 0.001  # Lower learning rate for more stability
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 2
  batch_size: 32  # Smaller batches for more stable gradient estimates

dataset:
  type: "mnist"
  images: "train-images-idx3-ubyte"
  labels: "train-labels-idx1-ubyte"

metadata:
  author: "James Couch"
  description: "Numerically stable OCR"
