name: "Single Dense Layer"

layers:
  - type: Input
    name: "input"
    output_shape: [1, 256]
    
  - type: Dense
    input_size: 256
    output_size: 512
    activation: tanh
    initializer: xavier


training:
  optimizer:
    type: adam
    learning_rate: 0.0001
    accumulation_interval: 4
    parameters:
      beta1: 0.9
      beta2: 0.999
      epsilon: 1e-8

  epochs: 1
  batch_size: 2

dataset:
  type: "function"
  dataset_size: 5000

metadata:
  author: "James Couch"
  description: "Single Dense Layer"
